// Les 55 domaines sémantiques, et l'icône de chacun.
//
// Un modèle nomme mal l'objet que désigne un mot — l'homonymie anglaise le
// piège — mais il **classe** très bien dans une liste fixe. Un mot concret
// garde donc son icône propre, plus précise ; tous les autres héritent de
// celle de leur domaine. C'est ce qui fait disparaître les tuiles
// typographiques sur le vocabulaire abstrait.
//
// La liste et les icônes ont été validées à l'œil (docs/design/domaines.html).
export const DOMAINS = [
  { id: "housing", label: "logement, appartement, loyer", icon: "apartment-building" },
  { id: "bills", label: "factures, charges, échéances", icon: "invoice" },
  { id: "money", label: "argent, prix, paiement", icon: "money" },
  { id: "banking", label: "banque, compte, virement", icon: "bank" },
  { id: "admin", label: "démarches, papiers, guichet", icon: "document" },
  { id: "health", label: "santé, symptômes, médecin", icon: "stethoscope" },
  { id: "pharmacy", label: "pharmacie, médicaments", icon: "pharmacy" },
  { id: "food", label: "nourriture, plats, cuisine", icon: "shakshuka" },
  { id: "drinks", label: "boissons, alcool", icon: "soju" },
  { id: "restaurant", label: "restaurant, commande, service", icon: "restaurant" },
  { id: "groceries", label: "courses alimentaires, supérette", icon: "bag-of-groceries" },
  { id: "shopping", label: "magasins, achats, boutiques", icon: "shopping-bag" },
  { id: "social", label: "sortir, voir du monde, se retrouver", icon: "group-of-people" },
  { id: "delivery", label: "livraison, colis", icon: "pizza-delivery-box" },
  { id: "transport", label: "métro, bus, trajets", icon: "subway-train" },
  { id: "driving", label: "voiture, taxi, route", icon: "taxi" },
  { id: "phone", label: "téléphone, forfait, appels", icon: "smartphone" },
  { id: "internet", label: "internet, applis, sites", icon: "globe" },
  { id: "neighbourhood", label: "quartier, voisins, immeuble", icon: "neighborhood-block-party" },
  { id: "weather", label: "météo, saisons", icon: "umbrella" },
  { id: "clothing", label: "vêtements, taille", icon: "t-shirt" },
  { id: "family", label: "famille, relations, amis", icon: "family" },
  { id: "home-life", label: "ménage, objets du quotidien", icon: "broom" },
  { id: "work", label: "bureau, entreprise, collègues", icon: "briefcase" },
  { id: "hierarchy", label: "titres, ancienneté, respect", icon: "crown" },
  { id: "meetings", label: "réunions, rendez-vous", icon: "calendar" },
  { id: "salary", label: "salaire, contrat, emploi", icon: "contract" },
  { id: "education", label: "études, examens, école", icon: "graduation-cap" },
  { id: "law", label: "justice, tribunaux, procès", icon: "gavel" },
  { id: "crime", label: "police, enquête, délits", icon: "handcuffs" },
  { id: "politics", label: "gouvernement, élections", icon: "elected-official" },
  { id: "military", label: "armée, service, sécurité", icon: "tank" },
  { id: "economy", label: "économie, marchés, inflation", icon: "graph" },
  { id: "business", label: "entreprises, secteurs", icon: "factory" },
  { id: "realestate", label: "immobilier, jeonse, marché", icon: "house-key" },
  { id: "society", label: "société, population, tendances", icon: "city" },
  { id: "media", label: "presse, télévision, culture", icon: "television" },
  { id: "sports", label: "sport, compétitions", icon: "basic-soccer-ball" },
  { id: "travel", label: "voyage, tourisme, aéroport", icon: "suitcase" },
  { id: "software", label: "logiciel, code, développement", icon: "code" },
  { id: "hardware", label: "matériel, puces, appareils", icon: "server" },
  { id: "ai", label: "intelligence artificielle, données", icon: "robot" },
  { id: "science", label: "recherche, découvertes", icon: "microscope" },
  { id: "energy", label: "énergie, environnement, climat", icon: "light-bulb" },
  { id: "space", label: "espace, astronomie", icon: "rocket" },
  { id: "speech", label: "parler, dire, demander", icon: "text-message-speech-bubble" },
  { id: "thought", label: "penser, croire, comprendre", icon: "brain" },
  { id: "emotion", label: "sentiments, humeur, ambiance", icon: "heart" },
  { id: "time", label: "temps, durée, moments", icon: "wall-clock" },
  { id: "quantity", label: "nombres, mesures, degrés", icon: "ruler" },
  { id: "change", label: "évolution, hausse, baisse", icon: "charts" },
  { id: "comparison", label: "comparer, semblable, différent", icon: "balance-scale" },
  { id: "movement", label: "aller, venir, déplacements", icon: "up-arrow" },
  { id: "rules", label: "règles, obligations, permissions", icon: "clipboard" },
  { id: "problem", label: "problèmes, erreurs, risques", icon: "warning-sign" },
]
